#ifndef SETTINGSERROR_H
#define SETTINGSERROR_H

#include <string>

enum SETTINGS_ERROR{
    SETTINGS_ERROR_NOERR,
    SETTINGS_ERROR_SYLLABLECOUNT_MAX_MIN,
    SETTINGS_ERROR_SYLLABLE_PATTERN,
    SETTINGS_ERROR_INTERSYLLABLE_PATTERN_EXCLUSION,
    SETTINGS_ERROR_ATTRIBUTE_ARGUMENT,
    SETTINGS_ERROR_WORDGROUP_ATTRIBUTE_UNKNOWN,
    SETTINGS_ERROR_NO_WORDGROUP_ATTRIBUTE,
    SETTINGS_ERROR_NO_LETTERGROUP,
    SETTINGS_ERROR_NO_SYLLABLEPATTERN,
    SETTINGS_ERROR_NO_WORDGROUP
};

std::string GetSettingsErrorMessage(SETTINGS_ERROR);
#endif // SETTINGSERROR_H
